name: NodeJS with Webpack

# on �κ���, � ���ǿ��� workflow�� ������ ������ �����մϴ�.
on:
  # step2 �귣ġ�� push �ൿ�� �� ������ workflow�� �����մϴ�.
  push:
    branches: ['step1']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: npm ci
      - run: npm run build

      - name: access to secrets
        run: |
          echo "API_KEY=$API_KEY" >> .env
        env:
          API_KEY: ${{secrets.API_KEY}}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
